import type { Metadata } from "next";
import Link from "next/link";
import style from "./styles.module.scss";
import Head from "next/head";
import './globals.css'

export const metadata: Metadata = {
  title: 'Electromagnit',
  description: "Generated by create next app",
};

export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
  return (
    <html lang="ua">
      <Head>
        <link
            rel="icon"
            href="/icon.png"
            type="image/<generated>"
            sizes="32x32"
        />
      </Head>
      <body className={style.container}>
        <header className={style.box}>
                <h2 className={style.title}>Оберіть мову | Выберете язык | Choose the language</h2>
                <div className={style.flex}>
                    <Link href="../../../../ua" className={style.language}>Українська</Link>
                    <Link href="" className={style.language}>Русский</Link>
                    <Link href="" className={style.language}>English</Link>
                </div>
            </header>
        <div>{children}</div>
      </body>
    </html>
  );
}
