import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import style from "./styles.module.scss";
import Loading from "./loading";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: {
    default: 'Electomagnit: вантажні електромагніти – тільки у нас!',
    template: '%s - Electromanit'
  },
  creator: "Daniil Andrieiev",
  description: "Generated by create next app",
  manifest: "https://electromagnit.com/ua",
  robots: {index: true, follow: true}
};

export default async function Layout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {

  return (
    <html lang="ua">
      <body>
        <header className={style.background}>
            <div className={style.container}>
                <div className={style.main}>
                    <Image className={style.logo} src="/Logo.png" alt="Logo Electromagnit" width={250} height={100}/>
                    <ul className={style.menu}>
                        <li className={style.list}>
                            <Link className={style.link} href="../../../ua">Головна</Link>
                        </li>
                        <li className={style.list}>
                            <Link className={style.link} href="../../../ua/Product">Продукт</Link>
                        </li>
                        <li className={style.list}>
                            <Link className={style.link} href="../../../ua/About">Про нас</Link>
                        </li>
                        <li className={style.list}>
                            <Link className={style.link} href="../../../ua/Contacts">Контакти</Link>
                        </li>
                    </ul>
                </div>
                <div className={style.main}>
                    <span className={style.questions}>З питаннями дзвоніть:<br />+4471234567890</span>
                    <span className={style.language}><Link className={style.languageLink} href="#">Русский</Link> / <Link className={style.languageLink} href="#">English</Link></span>
                </div>
            </div>
        </header>
        <Suspense fallback={<Loading />}>{children}</Suspense>
        <footer className={style.background}>
            <div className={style.container}>
                <div className={style.margin}>
                    <Image src="/Logo.png" alt="Logo ElectroMagnit" width={200} height={500} className={style.footerLogo}  />
                    <p className={style.copyright}>©2024 рік усі права захищені <br /><Link href="mailto:daniilandrieiev788@gmail.com">Створив сайт: Данііл Андрєєв</Link></p>
                </div>
                <div className={style.margin}>
                    <h2 className={style.title}>Контакти:</h2>
                    <ul className={style.footerMenu}>
                        <li className={style.box}>
                            <Image src="/telephone.png" alt="telephone" width={20} height={20} className={style.image}  />
                            <Link className={style.contacts} href="tel:+380964215130">+38 (096) 421-51-30</Link>
                        </li>
                        <li className={style.box}>
                            <Image src="/envelope.png" alt="envelope" width={20} height={15} className={style.image}  />
                            <Link className={style.contacts} href='mailto:europlastic2018@gmail.com'>europlastic2018@gmail.com</Link>
                        </li>
                    </ul>
                    <p className={style.text}>А також ви можете написати нам у <Link className={style.viber} href="viber://chat?number=%2b380964215130" >Viber</Link> або <Link className={style.telegram} href="https://t.me/%2b380964215130" >Telegram</Link></p>
                </div>
                <div className={style.margin}>
                    <h2 className={style.title}>Навігація:</h2>
                    <div>
                        <Link className={style.footerLink} href="../../../ua">Головна</Link>
                        <Link className={style.footerLink} href="../../../ua/Product">Продукт</Link>
                        <Link className={style.footerLink} href="../../../ua/About">Про нас</Link>
                        <Link className={style.footerLink} href="../../../ua/Contacts">Контакти</Link>
                    </div>
                </div>
                <div className={style.margin}>
                    <h2 className={style.title}>Наши проекты:</h2>
                    <Link className={style.color} href='/'><span className={style.grey}>Euro</span><span className={style.orange}>Plastic</span></Link>
                </div>
            </div>
        </footer> 
      </body>
    </html>
  );
}